### ISSUE TITLE
Looking for the celebA dataset split_img.npz

### ISSUE THREAD

**Issue by kaihuchen** [andrewliao11/CoGAN-tensorflow#2]
I'd like to the try this code on the celebA dataset, mainly for reproducing the faces+attributes test (see Figure 4 in the original paper). I noticed that there is a celebA class in utils.py that references a file named **split_img.npz**. Where can I find this file? It does not seems to be on the website http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html referenced in the original paper. Thanks!

**Comment by andrewliao11** [comment]
Hi I do implement this code in celebA before, but still WIP
I just committed my preprocess [code](https://github.com/andrewliao11/CoGAN-tensorflow/blob/master/parse_attr.py) and [metadata](https://github.com/andrewliao11/CoGAN-tensorflow/blob/master/list_attr_celeba.txt), hope it can help you
If you finish it, PR is welcomed!

**Comment by hinash88** [comment]
Hi,

Any help available for the listed issue?
