### ISSUE TITLE
error shows again over TF 1.1.0

### ISSUE THREAD

**Issue by westtalkzzz** [andrewliao11/CoGAN-tensorflow#3]
I tried it on v1.1.0 and got the following error:

//--------------------------------
ValueError: Variable g_bn0/g_bn0_2/moments_1/moments_1/mean/ExponentialMovingAverage/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
//--------------------------------

It seems you had fix it once?       

Thanks.

**Comment by andrewliao11** [comment]
can you try to use tf.0.11? So far, I have no plan to update this repo to the latest tf. However, any pull request is welcomed

**Comment by westtalkzzz** [comment]
Roger，thanks.(^_^)v

发自我的 iPhone

在 2017年7月4日，15:18，Andrew <notifications@github.com<mailto:notifications@github.com>> 写道：


can you try to use tf.0.11? So far, I have no plan to update this repo to the latest tf. However, any pull request is welcomed
