### ISSUE TITLE
ValueError: No gradients provided for any variable

### ISSUE THREAD

**Issue by leiup** [andrewliao11/CoGAN-tensorflow#4]
When running the training codes, there exists one problem: "ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients". How to solve it? Thanks.

**Comment by andrewliao11** [comment]
what's your tf version? Using tf.0.12 should be fine

**Comment by leiup** [comment]
I use tf 1.0. How to update the source codes? Thank you very much!

**Comment by andrewliao11** [comment]
Hi @leihe001 , in fact, I can't reproduce the error you encountered.
On the other hand, I just change the requirement to tf.0.12. I'll first close this issue and you can reopen it when you fail in tf.0.12 environment.

**Comment by leiup** [comment]
OK， thank you all the same!
